title = "Gitleaks development"
[extend]
useDefault = true

[allowlist]
paths = ["(?i).*\\.xml$",".*/recalculate_task.py",".*/do_one.py",".*/regrade_results.py",".*/analyze_results.py"]
regexes = [
    "exercise_key\\s*=\\s*\"",
    "course_key\\s*=\\s*\"",
    "question_key\\s*=\\s*",
]
